#!/bin/bash

# postinstall.sh
# pdfwriter
#
# Created by Simone Karin Lehmann on 30.08.10.
# Copyright 2010 Simone Karin Lehmann. All rights reserved.
# Modified 2016 Rodney I. Yager

# make symlink
ln -sf /Library/Printers/RWTS/PDFwriter/pdfwriter /usr/libexec/cups/backend/pdfwriter

# restrict running uninstall.sh to admin users only
chgrp admin /Library/Printers/RWTS/PDFwriter/uninstall.sh
chmod 750 /Library/Printers/RWTS/PDFwriter/uninstall.sh

# restart cupsd
launchctl unload /System/Library/LaunchDaemons/org.cups.cupsd.plist
launchctl load /System/Library/LaunchDaemons/org.cups.cupsd.plist

# install printer
lpadmin -p PDFwriter -E -v pdfwriter:/ -P /Library/Printers/PPDs/Contents/Resources/RWTS\ PDFwriter.gz -o printer-is-shared=false

# folder actions
ln -sf /Library/Printers/RWTS/PDFwriter/"Folder Actions"/"PDFwriter - Move PDFs Install.scpt" /Library/Scripts/"Folder Action Scripts"
ln -sf /Library/Printers/RWTS/PDFwriter/"Folder Actions"/"PDFwriter - Move PDFs.scpt" /Library/Scripts/"Folder Action Scripts"
